apiVersion: v1
kind: Service
metadata:
  name: recom-service
spec:
  selector:
    app: recom
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30003
  type: NodePort
